### ISSUE TITLE
Can't see stderr output

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/mage#103]
When I was writing a query module I wanted to catch an exception, write a note with `sys.stderr.write()` and raise an exception. When I do that, the exception is raised but I can't see the note I created, neither in Lab nor mgconsole.

**Comment by katarinasupe** [comment]
To reproduce:
Save the following JSON in test.json:
```
[
    {
        "labels": [
            "Person"
        ],
        "properties": {
            "name": "Ana"
        },
        "type": "node"
    }
]
```
Try `import_util.json procedure` with `test.json` file:

`CALL import_util.json("/path/to/test.json");`

This test file has a missing 'id' key. Inside procedure code there is `sys.stderr.write()`:
```
sys.stderr.write(
    (f"Each graph object needs to have 'type', 'properties' and 'id' keys.")
)
```
![Screenshot from 2022-01-27 17-22-45](https://user-images.githubusercontent.com/61758502/151400404-4bd0192a-86ba-4c94-af31-c5353d06fe6a.png)

As can be seen above, there is no error message in Memgraph Lab. I tried it in mgconsole too, and the same thing happens:

![Screenshot from 2022-01-27 17-26-32](https://user-images.githubusercontent.com/61758502/151400876-e316ff1d-8c84-422c-b923-6cf41d54c166.png)

**Comment by jmatak** [comment]
The conclusion of this issue is that it is impossible to send a Bolt result by writing to `stderr`. Therefore, changes were made to raise appropriate exception once it happens. THis can be closed @katarinasupe ?
