### ISSUE TITLE
[BUG] Cycles.get() does not return

### ISSUE THREAD

**Issue by Orbifold** [memgraph/mage#181]
**Describe the bug**
The basic cycles query CALL cycles.get() YIELD cycle_id, node; on the Capital Cities dataset does not return. Has only a couple of hundred nodes, so that should not be an issue. 

**To Reproduce**
- Load the Capital Cities dataset in MemGraph.
- Run the `CALL cycles.get() YIELD cycle_id, node;` query.

**Expected behavior**
The query should return the cycles contained in the graph.

**Comment by antoniofilipovic** [comment]
Thanks for reporting the issue! We will check out what is the problem and get back to you.

**Comment by antoniofilipovic** [comment]
Hi @Orbifold,

sorry for taking it a bit longer. Thing with cycles module is that it tries to find all the cycles and complexity is exponential with number of edges, if I am not wrong.

So, one solution would be to restrict number of cycles. Let me know what you think. If you have any additional questions, feel free also to reach me on [Discord](https://discord.gg/memgraph), as it is easier to chat there, I am afilipovic#8994.

**Comment by Josipmrden** [comment]
Since `KILL TRANSACTION` and `SHOW TRANSACTION` will be available in Memgraph v2.7, we will add the corresponding changes to all the possibly long-running algorithms to be able to be shutdown in case of slow performance, therefore making the database not crash but to gracefully stop the transaction.

**Comment by Josipmrden** [comment]
Setting the milestone to v1.7.1, PR will be linked additionally

**Comment by imilinovic** [comment]
Closed due not being a bug and KILL TRANSACTION and SHOW TRANSACTION being available now.
