### ISSUE TITLE
[BUG] `distance_calculator.multiple` returned field has incorrect name of `distance` instead of `distances`.

### ISSUE THREAD

**Issue by horatiubota** [memgraph/mage#190]
**Describe the bug**
In the `distance_calculator.multiple` procedure, the returned field is called `distance` instead of `distances` as per documentation: https://github.com/memgraph/mage/blob/2a89b68ce107ec701732c67d4c9b251fc521db52/python/distance_calculator.py#L56.

**Expected behavior**
Returned field should be called `distances` not `distance`.

**Comment by Josipmrden** [comment]
@horatiubota added task to backlog. This is an easy fix and should be corrected soon. Will message you here about the details of the solution, and possible updates.

**Comment by horatiubota** [comment]
@Josipmrden thanks! Found the issue in this bug report by poking around the `distance_calculator` module - mostly because I'm interested in this issue: https://github.com/memgraph/mage/issues/189. If you have some pointers on the related issue, please ping me.

**Comment by Josipmrden** [comment]
@horatiubota you have a message there also, feel free to message me there, since I can not add you directly as participant and therefore not tag you as well

**Comment by antoniofilipovic** [comment]
This is fixed in the new C++ module, so I will close this.
