### ISSUE TITLE
[FEATURE] Cypher subqueries from python query modules 

### ISSUE THREAD

**Issue by jhb** [memgraph/mage#192]
When writing a python query module, it would be nice if I could somehow run cypher queries from the function or procedure code. 

My use case is reimplementing a python algorithm that contains repeated queries to the database using cypher. This way I could keep the overall logic and approach, and just shift all of it to the server side.

A nonsensical example would look like this:

```python
import mgp

@mgp.function
def my_example(context: mgp.FuncCtx,
               argument: mgp.Any):
    for _ in range(argument):
        result = mgp.run('Match (n:foo)-->(m:bar) return n, m')
        for record in result:
            n = record['n']
            ...  # do something interesting here
```

So its about querying the database and using the results within the function/procedure.

**Comment by Josipmrden** [comment]
Hello @jhb !

Please see the docs here so I can fully understand your inquiry https://memgraph.com/docs/memgraph/reference-guide/streams/transformation-modules/api/python-api

This is the transformation module which we use when ingesting data from a Kafka topic. There is some data coming in (in batches), and the output is a list of commands that will be executed in a transaction, resulting in a continuous stream.

Is your intention to output a list of queries from `CALL my_procedure.something(...)`

And can you please provide some steps of a fictional use case, before I put it to backlog or do any internal discussions with the team :)

Regards!

**Comment by Josipmrden** [comment]
Currently the output of procedures (not transformations), do not support additional cypher execution

**Comment by jhb** [comment]
Updated the description, it hopes it helps clarify the use case.

**Comment by antoniofilipovic** [comment]
hi @jhb,

sorry for keeping you waiting. 

This is not possible to implement easily due to the current Memgraph infrastructure. You can't call a query from the query module. I think it won't be in the near plan because it would require reorganizing a lot of stuff inside Memgraph. And therefore it is more a Memgraph issue than MAGE issue. If there is no other way for you to do this, I am happy to jump on a call and discuss what can we do more to help you. Please feel free to drop us other questions you have on discord or contact me directly. My username there is `afilipovic#8994 `.
  
Thanks for waiting and for the nice description of a feature request. We will definitely keep this in mind. 

Best,
Antonio

**Comment by jhb** [comment]
Hi Antonio, thanks a lot for your feedback (which I find still quite fast). 

Would have been nice, but I can also see how this could potentially lead to never ending logic circles. ;-)

**Comment by Josipmrden** [comment]
Hey @jhb , today we were discussing something in the team, and realized we could actually make GQLAlchemy available in the python interpreter (when using the Docker instance). That would allow for execution of independent queries inside a query module. Check out the snippet below:

```
import mgp
from gqlalchemy import Memgraph

@mgp.read_proc
def query(
  context: mgp.ProcCtx,
  query: str
) -> mgp.Record(vertex_count=int):
  memgraph = Memgraph()

  results = memgraph.execute_and_fetch(query)
  size = len(list(results))

  return mgp.Record(vertex_count=size)
```

we're currently discussing where exactly should we put it, directly in Memgraph image or in memgraph-mage which can then be executed in memgraph-platform as well. Anyways, we'll keep you posted :D

**Comment by jhb** [comment]
This is excellent news, very exiting indeed! I am very much looking forward to see that happening!

**Comment by Josipmrden** [comment]
GQLAlchemy is available to do such queries, please try it out @jhb, if any of the things reappear, please do reopen the issue! :)
