### ISSUE TITLE
Running `community_detection_online.set()` causes Memgraph to crash

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/mage#219]
I ran `community_detection_online.set()` on a large dataset (around 200k nodes, 1M relationship) on a running Memgraph instance with 24 GB RAM. Memory spiked and caused Memgraph to crash. It would be great if, in that case, Memgraph does not crash, but the transaction is stopped instead.

**Comment by gitbuda** [comment]
Most likely related memgraph/mage#379 memgraph/memgraph#955
