### ISSUE TITLE
[BUG] - Newest Memgraph 2.10 image is not present in Mage memgraph-mage:1.9-memgraph-2.10.0-dev

### ISSUE THREAD

**Issue by antejavor** [memgraph/mage#319]
**Describe the bug**
Mage's latest image doesn't have latest Memgraph image inside. 

**To Reproduce**
`docker run -it -p 7687:7687 -p 7444:7444 memgraph/memgraph-mage:1.9-memgraph-2.10.0-dev`
`SHOW VERSION;`
Returns 2.9

**Expected behavior**
Returns 2.10

![image](https://github.com/memgraph/mage/assets/18125448/31749ebd-389b-4061-a142-9d0c868f3041)

**Comment by lsghmachineuser** [comment]
Same in `memgraph/memgraph-mage:1.9-memgraph-2.10.0`

**Comment by alex-linx** [comment]
Same in memgraph/memgraph-mage:1.9-memgraph-2.10.0

**Comment by gitbuda** [comment]
I think we didn't properly update all memgraph versions when mage v1.9 was released:
* [v1.8 prepare PR](https://github.com/memgraph/mage/pull/243/files) -> was OK
* [v1.9 prepare PR](https://github.com/memgraph/mage/pull/288/files) -> NOT OK, only the submodule was updated but it seems like we missed all memgraph versions
* [v1.10 prepare PR](https://github.com/memgraph/mage/pull/323/files) -> should be OK
