### ISSUE TITLE
[BUG] libmgclient.so is being copied with the query modules into the target location during build.

### ISSUE THREAD

**Issue by gvolfing** [memgraph/mage#357]
Support for `mgclient` has been added in [this](https://github.com/memgraph/mage/pull/221/) PR.
This issue is that the created `libmgclient.so` shared object is being copied into the target location when the setup script is called. 
This is an issue because when we load the mage modules from memgraph, it will attempt to load `libmgclient.so` as well which was never intended to be used as a query module.

**Comment by antoniofilipovic** [comment]
Done
