### ISSUE TITLE
[BUG] neighbors.at_top producer：Query failed: neighbors.at_hop: There are no nodes at hop 1.

### ISSUE THREAD

**Issue by penghs520** [memgraph/mage#374]
Can this return an empty set without throwing an exception

![image](https://github.com/memgraph/mage/assets/52020193/de19d478-2da5-432b-a2d7-c5a5c2ee96bf)

**Comment by adwu73** [comment]
Because in our case, some node may not have neighbours.. We want to modify the code like this, do you think it will work?

![image](https://github.com/memgraph/mage/assets/1219775/4060d71e-097e-47a4-ba33-01f0958f2b1a)

**Comment by matea16** [comment]
Hi @penghs520 and @adwu73, I see there was a similar [conversation on Discord](https://discord.com/channels/842007348272169002/890968933040009276/1158768850289045536) on this. Was the answer helpful, have you been able to resolve your issue?

**Comment by penghs520** [comment]
The discord solution hasn't solved my problem yet

**Comment by mpintaric55334** [comment]
Hi all. We have decided to implement returning of empty data instead of exception.

**Comment by katarinasupe** [comment]
@matea16 do you know if this is resolved and can this issue be closed?

**Comment by matea16** [comment]
@katarinasupe yes, this issue can be closed, it was resolved with the previously mentioned fix
