### ISSUE TITLE
Build apoc.schema.assert

### ISSUE THREAD

**Issue by hal-eisen-MG** [memgraph/mage#409]
Potential customer says that we're missing apoc.schema.assert

**Comment by katarinasupe** [comment]
We have another community report -> https://discord.com/channels/842007348272169002/890969003374289016/1171708792040329236 
I would like to emphasize that there is no easy way to drop all constraints/indexes without this. The workaround combination of running and passing `SHOW INDEX INFO;` and `DROP INDEX` queries. Similar goes for the constraints. 
We have that capability in GQLAlchemy, but if users are migrating, this is probably not their current driver used.

**Comment by hal-eisen-MG** [comment]
@as51340 How much more time do you need to finish this?

**Comment by as51340** [comment]
I will close this issue here and open it on Memgraph repo.
