### ISSUE TITLE
Build apoc.refactor.mergeNodes alternative 

### ISSUE THREAD

**Issue by antejavor** [memgraph/mage#410]
Add MAGE alternative: [mergeNodes](https://neo4j.com/labs/apoc/4.3/graph-updates/graph-refactoring/merge-nodes/ )

**Comment by antoniofilipovic** [comment]
Don't we have that?https://memgraph.com/docs/advanced-algorithms/available-algorithms/merge

**Comment by antejavor** [comment]
Aha!  @antoniofilipovic, it is just being used a bit differently than the Neo4j version. Thanks for providing the info @antoniofilipovic!

**Comment by antejavor** [comment]
Aha! @antoniofilipovic, it is just being used a bit differently than the Neo4j version. Thanks for providing the info @antoniofilipovic!
