### ISSUE TITLE
Build apoc.text.regexGroups alternative 

### ISSUE THREAD

**Issue by antejavor** [memgraph/mage#412]
Build MAGE alternative: [regexGroups](https://neo4j.com/labs/apoc/4.3/overview/apoc.text/apoc.text.regexGroups/)

**Comment by antepusic** [comment]
Here’s the implementation of `apoc.text.regexGroups`: https://neo4j.com/labs/apoc/4.3/overview/apoc.text/apoc.text.regexGroups/
