### ISSUE TITLE
Docker versioning [VERSION] 

### ISSUE THREAD

**Issue by jmatak** [memgraph/mage#43]
Currently, there is no adequate versioning system to match Memgraph's version that the MAGE Docker image is based on. The proposal is to add versioning similar to the Memgraph image, so users could easily access the legacy versions.

**Comment by MasterMedo** [comment]
If I understand it correctly, when we're pushing the latest docker image we take the latest memgraph image.
We should take the latest memgraph image when pulling (if possible), and build the mage docker tag locally.

I propose having completely independent versioning systems for Memgraph and MAGE.

**Comment by jmatak** [comment]
Independent systems of versioning is what I stand for as well. 

Interesting proposition of building the MAGE docker tag locally. However, it might me more useful to make a tag release of MAGE with current version of Memgraph whenever a new one hits the production.
