### ISSUE TITLE
Missing text function from MAGE

### ISSUE THREAD

**Issue by matea16** [memgraph/mage#448]
In the newest version, the `text` function is missing, user reported he was using it before updating the version and noticed it was missing. 

[Source](https://www.notion.so/memgraph/Ron-Greve-Cloud-User-Interview-2de22b8848d54ef9a4c95fe2693bd746)

**Comment by antejavor** [comment]
+ 1 from the community: https://discord.com/channels/842007348272169002/842008652377751582/1236942628944220160

**Comment by vimagick** [comment]
Please add `text` function back. Thanks!
