### ISSUE TITLE
Missing link_prediction with GNN in MAGE v1.14.0 and newer versions

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/mage#469]
Removal happened under #443 under `Dockerfile.release` -> starting from memgraph v2.21, the modules should start working (fix done under https://github.com/memgraph/memgraph/pull/2347) -> revert the change done under v1.14.1 of Mage 😄

**Comment by katarinasupe** [comment]
+1 from the community ([source](https://discord.com/channels/842007348272169002/890968933040009276/1234697075686510602))

**Comment by katarinasupe** [comment]
+1 from the community ([source](https://www.notion.so/memgraph/Mark-from-okg-com-0c3c084edfed4478b88de13b41ad4155))

**Comment by gvolfing** [comment]
@katarinasupe Same here as in https://github.com/memgraph/mage/issues/470 what does it mean that the module is missing?

**Comment by katarinasupe** [comment]
Severity was higher due to this comment - https://github.com/memgraph/documentation/issues/756#issuecomment-2107671194

**Comment by gitbuda** [comment]
@imilinovic I think you mentioned today that you plan to put the modules back 🤔 Assigning you under this issue, please link the PR 🙏
