### ISSUE TITLE
Missing node_classification with GNN in MAGE v1.14.0 and newer versions

### ISSUE THREAD

**Issue by katarinasupe** [memgraph/mage#470]

**Comment by katarinasupe** [comment]
+1 from the community ([source](https://www.notion.so/memgraph/Mark-from-okg-com-0c3c084edfed4478b88de13b41ad4155))

**Comment by gvolfing** [comment]
@katarinasupe What does it mean that the module is missing? From where? Is it not loaded into Memgraph successfully? I'm not sure if I understand what the issue is based on the title only.

**Comment by katarinasupe** [comment]
Severity was higher due to this comment - https://github.com/memgraph/documentation/issues/756#issuecomment-2107671194
