### ISSUE TITLE
[BUG] Elasticsearch client only connects via TLS 

### ISSUE THREAD

**Issue by nagi49000** [memgraph/mage#496]
**Describe the bug**
Elasticsearch client only works with TLS and username supplied, even though underlying client has more options. This means that I can't connect via http to elastic for testing

**To Reproduce**
1. Connect to an elastic instance from memgraph Cypher editor:
```
CALL elastic_search_serialization.connect("http://elasticsearch:9200", null, "", "")
YIELD connection_status
RETURN connection_status;
```
3. Message comes back saying that only TLS is supported

**Expected behavior**
Connect to elasticsearch over http succesful

**Screenshots**

**Additional context**
Fix is easy and has been tested.
In https://github.com/memgraph/mage/blob/main/python/elastic_search_serialization.py
Add on line 2 an import for Union:
```
from typing import Any, List, Dict, Tuple, Union
```
On line 228, add default vars an extend types
```
@mgp.read_proc
def connect(
        elastic_url: str, ca_certs: Union[str, None]=None, elastic_user: str="", elastic_password: str=""
) -> mgp.Record(connection_status=mgp.Map):
```

**Comment by antejavor** [comment]
Hi @nagi49000, thanks for opening the issue and communicating this.

**Comment by nagi49000** [comment]
PR up - https://github.com/memgraph/mage/pull/504
