### ISSUE TITLE
betweenness_centrality returns a score with typo

### ISSUE THREAD

**Issue by antonio2368** [memgraph/mage#59]
I'm not sure if there is a specific reason for it, but the `betweenness_centrality` module returns the score as `betweeenness_centrality` (3 e instead of 2).
On the [docs page](https://docs.memgraph.com/mage/query-modules/cpp/betweenness-centrality/) the same thing is repeated which made me question if it was accidental or intentional.

**Comment by jmatak** [comment]
It's a typo. Interesting how that ended up not only in docs but also in end2end tests.
